
GRAPH_as_mean_session_length_in_week_day = "as_mean_session_length_in_week_day.xlsx"
GRAPH_mean_active_time_per_day_with_std_of_every_user = "mean_active_time_per_day_with_std_of_every_user.xlsx"
GRAPH_mean_active_time_per_day_with_std_of_every_user_pure = "mean_active_time_per_day_with_std_of_every_user_pure.xlsx"
GRAPH_mean_session_count_per_day_with_std_of_every_user = "mean_session_count_per_day_with_std_of_every_user.xlsx"
GRAPH_mean_session_count_per_day_with_std_of_every_user_pure = "mean_session_count_per_day_with_std_of_every_user_pure.xlsx"
GRAPH_mean_session_length_with_std_of_every_user = "mean_session_length_with_std_of_every_user.xlsx"
GRAPH_mean_session_length_with_std_of_every_user_pure = "mean_session_length_with_std_of_every_user_pure.xlsx"
GRAPH_mean_session_length_vs_session_count_per_day_of_every_user = "mean_session_length_vs_session_count_per_day_of_every_user.xlsx"
GRAPH_user_mean_active_time_per_day_vs_total_mean_active_time_per_day = "user_mean_active_time_per_day_vs_total_mean_active_time_per_day.xlsx"
GRAPH_mean_interactive_length_in_hour_for_all_users = "mean_interactive_length_in_hour_for_all_users.xlsx"
GRAPH_mean_IS_count_in_hour_per_day_for_all_users = "mean_IS_count_in_hour_per_day_for_all_users.xlsx"
GRAPH_all_interactions_cdf = "all_interactions_cdf.xlsx"

SS_APP_OPEN_NUM_IDX = 0
SS_SESSION_LENGTH_IDX = 3
SS_SESSION_START_TIME_IDX = 2
